### ISSUE TITLE
Last update (#12) causes streams to be too quiet & range does not work

### ISSUE THREAD

**Issue by RanchTheDeer** [Vurv78/WebAudio#13]
The last update (#12) causes streams to have very a low volume (the volume does change when webaudio:volume() is used, but the stream is very quiet), and the audio can be heard regardless of distance from E2 to player. Setting the range seems to make no difference to this.

**Comment by Vurv78** [comment]
I was hoping this wouldn't be the case but I couldn't find any documentation as to why Set3DFadeDistance is so jank, it was working fine for me, maybe I'll have to make a modular ``think`` hook system for the receiver which will be annoying..

**Comment by RanchTheDeer** [comment]
I noticed that in the code, the values seem to be very strange for the set3DFadeDistance function
`bass:Set3DFadeDistance(self.radius, 1000000000)`
The radius seems to be set to the wrong value? This would modify the *minimum* radius, not the *maximum* radius, surely?

**Comment by Vurv78** [comment]
Yes, doing the opposite (which would seem correct) yielded the same results as you are having for me. I heard the sound across the map

**Comment by Vurv78** [comment]
Very weird so yeah we'll just manually set the volume like streamcore does. Either way we needed to do this in order to add #11
