### ISSUE TITLE
Make a new showcase video

### ISSUE THREAD

**Issue by Vurv78** [Vurv78/WebAudio#18]
Anyone can do this, but I will probably get to it at some point.
I want a better quality video to upload to the workshop / youtube that will showcase the new features we've added like time elapsed, etc. If we did this after adding getFFT that'd be great to showcase it as well

// Show a music player or something

**Comment by Kapppa** [comment]
What are you looking for? I have made a pretty in-depth music player using WebAudio. I also have a FFT display (really laggy using EGP).

**Comment by Vurv78** [comment]
Pretty much exactly that, just want to have a video that shows the mountain of features this has over streamcore and how much more stuff you can do with this. Would be perfect if you could make a video

**Comment by Kapppa** [comment]
https://www.youtube.com/watch?v=L91eGDgT8pY Got some stuff in it

**Comment by Vurv78** [comment]
Awesome, made it the first video on the workshop page, thanks
Also noticed that IO 👀

For anyone who wants to submit others in the future make a [discussion](https://github.com/Vurv78/WebAudio/discussions), closing this doesn't mean I won't accept others on the page
