### ISSUE TITLE
Newest release errors -attempt to index local 'Common' (a nil value)

### ISSUE THREAD

**Issue by RanchTheDeer** [Vurv78/WebAudio#29]
```
There was an error loading the custom/webaudio.lua extension. Please report this to its developer.
entities/gmod_wire_expression2/core/custom/webaudio.lua:9: attempt to index local 'Common' (a nil value)
```
Looks like `WebAudio.Common` isn't initialised with a value on first run for whatever reason

Edit: Another error cropped up whilst testing:
```
[webaudio-main] addons/webaudio-main/lua/autorun/webaudio.lua:66: attempt to call method 'disassemble' (a nil value)
  1. unknown - addons/webaudio-main/lua/autorun/webaudio.lua:66
```

Seems like the functions are being called for in the code before they are defined

**Comment by Vurv78** [comment]
Can you test it out now? It seems something on your server didn't let webaudio load the first time, which made disassemble not exist, and we tried to call it. I made it check for disassemble so it should let you debug it now. Also E2 checks if webaudio is loaded, if not then it includes it.

**Comment by RanchTheDeer** [comment]
Latest push works with no issues - everything works as intended.
