### ISSUE TITLE
Audio Parenting Issue

### ISSUE THREAD

**Issue by MrKeating07051** [Vurv78/WebAudio#49]
**setParent( )** works instead of **parentTo( )**. Plays on the E2 chip instead.

**Comment by Vurv78** [comment]
parentTo is an alias, so as far as I know it's impossible for setParent to work while parentTo doesn't, or it's an issue with wiremod

Just tested in [the latest commit](https://github.com/Vurv78/WebAudio/commit/1d364ea2cfa177131f8041e2d9fd55a758de487d) and it seems to work, can you post a code snippet ?

**Comment by Vurv78** [comment]
Nevermind fixed the issue. I added a change to make webaudio streams parent to the chip by default on ``xwa:play()`` if ``xwa:setPos()`` was never called but also should've checked if they ``xwa:setParent()`` previously.
