### ISSUE TITLE
Volume and Pause not Working

### ISSUE THREAD

**Issue by oneandonlyjason** [Vurv78/WebAudio#50]
**Describe the bug**
The Pause and Volume Function doesnt work

**To Reproduce**
I used the Following E2 Code:
```Audio = webAudio("https://ytdl.jason-m.net/download/tnRxocc7PpA.mp3")
Audio:play()
Audio:setVolume(300)
Audio:update()
Audio:pause()
```

**Expected behavior**
I would think that with this Code the Stream Starts, the Volume gets increased to 300% and it Stops the Stream Again.
But in direct Comparision to a Stream with 100% Volume it is not any Louder and the pause() is ignored also. I would expect that the Stream Stops but it just keeps playing

**Desktop (please complete the following information):**
 - OS: Windows
 - Gmod Branch: x86-64

**Comment by Vurv78** [comment]
Use the ``@strict`` directive and your chip should throw an error. This code probably doesn't work as you are going over this burst limit

Also ``xwa:pause()`` ``xwa:play()`` and ``xwa:update()`` all send the information to the client so you don't need to do ``xwa:update()`` and then ``xwa:pause()`` right after, you can just do ``xwa:pause()``

**Comment by oneandonlyjason** [comment]
Yeah this was Just an Example to See if i make anything wrong in my normal Chip

My Normal Chip Starts a Stream when i use a Command.
When i use the Stop Command the Chip Executes:
`Music:stop()`

Where Music is my WebStream Object. I can also see that this Part of the Code Executes because everything Visual after that Command Executes correctly
Just the Music does not stop, it just keeps Playing. And Same for the Volume in the End
When i activate the @strict directive it also doesnt throw an Error it just doesnt pause the Music

**Comment by oneandonlyjason** [comment]
Ok i figured out what was wrong... And its kinda my Bad because im not used to OOP in E2. I needed a `@persist Stream:webaudio` so that the Object he would use is the Same Everytime i guess. My Guess is that the Object was not Persist and Global per Default so he didnt find it when he Tried to Stop the Stream

**Comment by Vurv78** [comment]
Need to make WebAudio properly give an error if you try and use it while it isn't valid then. (At least with ``@strict`` on)
