### ISSUE TITLE
No Function with Newest Version anymore

### ISSUE THREAD

**Issue by oneandonlyjason** [Vurv78/WebAudio#53]
Since the Server Updated to the Newest Workshop Version (v0.6.2) a Couple Days Ago the Addon has no Function anymore. This is the Error Message that Shows in E2

![Image1](https://push.jason-m.net/QhbCR4ljfs.jpg)

The E2Helper Search is also empty
![Image2](https://push.jason-m.net/qzKIRsAmOR.jpg)
![Image3](https://push.jason-m.net/w6nHPY72VX.jpg)

**Comment by Andrew-Eathan** [comment]
can comfirm, something about an invalid number 0b00000000000something, i can't say where this happens but it does

**Comment by Vurv78** [comment]
yup some versions of gmod are on LuaJIT 2.0.4 while x86-64 is on 2.1.0-beta3, horrible

**Comment by oneandonlyjason** [comment]
Linux Server here, if that makes any Difference
